[tool.black]
line-length = 120
include = '\.pyi?$'
exclude = '''
/(
  kubernetes_pydantic/generated
  | \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | venv
)/
'''

[tool.pytest.ini_options]
# addopts = '--cov-branch --cov-report term-missing --cov'
testpaths = ["kubernetes_pydantic/"]
python_files = ["*_test.py"]
