name: CI-Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: "Type Check and Lint"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build
        run: |-
          docker image build -t k8s-pydantic -f Dockerfile.test .
          docker run --rm k8s-pydantic pip freeze

      - name: Test pyright
        run: docker run --rm k8s-pydantic pyright src

      - name: Test flake8
        run: docker run --rm k8s-pydantic flake8 -v src

      - name: Test black
        run: docker run --rm k8s-pydantic black --check src

      - name: Test pytest
        run: docker run --rm k8s-pydantic pytest --cov-branch --cov-report term-missing --cov
